apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ghcr-test
  name: ghcr-test
  namespace: default
spec:
  nodeName: $DEBUG_NODE
  containers:
  - name: ghcr-image
    image: ghcr.io/hsunhsunwenfang/k8s-tools:main
    volumeMounts:
    - mountPath: /host
      name: host-root
    securityContext:
      privileged: true
  # imagePullSecrets:
  # - name: hsunhsunwenfang-ghcr-secret
  # securityContext:
  #   runAsUser: 1000
  #   runAsGroup: 3000
  #   fsGroup: 2000
  volumes:
  - name: host-root
    hostPath:
      path: /
      type: ""
